blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/your-username/smart-rds-viewer/blob/main/README.md
    about: Check the README for usage instructions and examples
  - name: 🔒 Security Vulnerability
    url: mailto:hello@kratik.dev
    about: Report security vulnerabilities privately via email
  - name: 💬 General Questions
    url: https://github.com/your-username/smart-rds-viewer/discussions
    about: Ask questions and discuss ideas with the community